name: Test checkout

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout
        id: sha
        uses: actions/checkout@v2
        with:
          repository: step-security/secure-workflows
          path: secure-workflows

      - run: echo "${{ github.sha }}+${steps.sha.outputs.GITHUB_SHA}"
