name: Test checkout

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout-repo1
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout
        id: checkout-repo2
        uses: actions/checkout@v3
        with:
          repository: step-security/secure-workflows
          ref: main
          fetch-depth: 0

      - name: Test gitleak
        run: echo "AKIAIMNOJVGFDXXXE4OA"

      # - name: test
      #   uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:4.0.1

      # - name: Fetch latest commit SHA
      #   id: latest-commit
      #   run: |
      #     sha=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/step-security/secure-workflows/commits | jq -r '.[0].sha')
      #     echo "SHA=${{ github.sha }}$sha" >> $GITHUB_ENV

      # - name: Print sha
      #   run: echo "$commit"
      #   env:
      #     commit: ${SHA}

      # - name: Print logs
      #   run: echo ${{ toJson(steps.checkout-repo2.outputs) }}

      # - name: Print logs
      #   run: echo ${{ toJson(steps.checkout-repo1.steps) }}

