name: Test checkout

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout-repo1
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout
        id: checkout-repo2
        uses: actions/checkout@v2
        with:
          repository: step-security/secure-workflows
          path: secure-workflows
          ref: main
          fetch-depth: 0

      - name: Print sha
        run: echo "${{ github.sha }}${{steps.checkout-repo2.outputs.ref }}"
