name: Test checkout

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout-repo1
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout
        id: checkout-repo2
        uses: actions/checkout@v2
        with:
          repository: step-security/secure-workflows
          path: secure-workflows
          fetch-depth: 0

      - run: echo "${{ github.sha }}${{steps.checkout-repo2.outputs.sha }}"
      - run: echo "${{steps.checkout-repo1.outputs.sha }}"
      - run: echo "${{steps.checkout-repo2.outputs.sha }}"
