name: Test checkout

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout-repo1
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Checkout
        id: checkout-repo2
        uses: actions/checkout@v3
        with:
          repository: step-security/secure-workflows
          ref: main
          fetch-depth: 0

      - name: Get latest commit
        id: latest-commit
        uses: jakejarvis/get-latest-commit@v1
        with:
          repository: step-security/secure-workflows

      - name: Print sha
        run: echo "${{ github.sha }}${{steps.latest-commit.outputs.sha }}"

      # - name: Print logs
      #   run: echo ${{ toJson(steps.checkout-repo2.outputs) }}

      # - name: Print logs
      #   run: echo ${{ toJson(steps.checkout-repo1.steps) }}

