name: Test checkout

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout-repo1
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Checkout
        id: checkout-repo2
        uses: actions/checkout@v3
        with:
          repository: step-security/secure-workflows
          ref: main
          fetch-depth: 0

      - name: Integration test
        uses: docker://ghcr.io/step-security/integration-test/int@sha256:62c23b778fb28a71129562418a4f4ee4ff391401481ddb8b6a7d1b58efc2f533
        env:
          PAT: ${{ secrets.PAT }}

      # - name: Fetch latest commit SHA
      #   id: latest-commit
      #   run: |
      #     sha=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/step-security/secure-workflows/commits | jq -r '.[0].sha')
      #     echo "SHA=${{ github.sha }}$sha" >> $GITHUB_ENV

      # - name: Print sha
      #   run: echo "$commit"
      #   env:
      #     commit: ${SHA} 

      # - name: Print logs
      #   run: echo ${{ toJson(steps.checkout-repo2.outputs) }}

      # - name: Print logs
      #   run: echo ${{ toJson(steps.checkout-repo1.steps) }}

