name: Test checkout

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: Checkout-repo1
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout
        id: Checkout-repo2
        uses: actions/checkout@v2
        with:
          repository: step-security/secure-workflows
          path: secure-workflows

      - run: echo "${{ github.sha }}${{steps.Checkout-repo2.outputs.sha }}"
      - run: echo "${{steps.Checkout-repo1.outputs.sha }}"
      - run: echo "${{steps.Checkout-repo2.outputs.sha }}"
